apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secure-service.fullname" . }}
  labels:
    {{- include "secure-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "secure-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "secure-service.selectorLabels" . | nindent 8 }}
      {{- if or .Values.podAnnotations .Values.telemetry.prometheus.enabled }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.telemetry.prometheus.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.telemetry.prometheus.path | quote }}
        prometheus.io/port: {{ .Values.telemetry.prometheus.port | quote }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ default (include "secure-service.fullname" .) .Values.serviceAccount.name }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.platform.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "secure-service.name" . }}
          {{- if .Values.image.digest }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          securityContext:
            {{- toYaml .Values.platform.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.platform.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: http
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
