apiVersion: v1
kind: Service
metadata:
  name: {{ include "secure-service.fullname" . }}
  labels:
    {{- include "secure-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.platform.serviceType }}
  ports:
    - name: http
      port: {{ .Values.developer.servicePort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "secure-service.selectorLabels" . | nindent 4 }}
