replicaCount: 2

image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: "6.7.1"
  digest: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 9898

telemetry:
  prometheus:
    enabled: true
    path: /metrics
    port: 9898

podAnnotations: {}

platform:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

livenessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /readyz
  initialDelaySeconds: 3
  periodSeconds: 5

startupProbe:
  path: /healthz
  periodSeconds: 5
  failureThreshold: 12
