name: Lint Helm chart defaults

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    uses: DevOpsDerek/workflows/.github/workflows/lint/helm.yml@5ecebff22598835cbf5ccd7bfa07c036cce22ee9
    with:
      helm-version: 3.17.3
      chart-path: charts/secure-service
